[Settings]
#MAC address of the device to wake
mac_address = 
#Phone number that will send SMS (international format)
trusted_number = 
#Maximum message capacity of your SIM card/device
max_messages = 